<a href="https://colab.research.google.com/github/pondbaahh/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np # package สำหรับทำงานกับ ข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ Matrix)

### Numpy Array

### สร้าง numpy array (matrix)

In [5]:
np_a = np.array([[1,2,3],[4,5,6]]) #สร้าง numpy array ที่มี2 แถว 3 หลัก

In [6]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np_a.shape

(2, 3)

In [11]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

##matrix transpose

In [12]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

##สร้าง matrix เริ่มต้น (zeros,ones)

In [13]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
np_200 = 200*np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง Matrix random 

In [16]:
np.random.randn(5,5)  #random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[-0.37506062,  1.43856078,  0.3402728 ,  1.01830055,  0.49687196],
       [-0.35933056,  0.47299127, -0.52052635,  1.84348134, -0.27688228],
       [ 0.73725897, -0.64762885, -0.90493307,  0.68803604, -0.90497204],
       [ 0.63560164,  0.16164609,  0.52121627,  0.17335986,  0.38455772],
       [ 0.53490969, -0.10101488, -0.67385867, -1.91232042, -0.24764149]])

In [17]:
2+(5*np.random.randn(3,3)) #random เลขมาจาก normal distribution ที่มี mu=2 std=5

array([[-1.0985793 ,  0.93659044,  6.72115341],
       [ 5.69688431,  4.01923209, -7.48736254],
       [ 6.13172159,  0.57345745,  2.74354289]])

In [18]:
np.random.randint(5,11,(4,5)) #random เลขจำนวนเต็ม ระหว่าง[5,11] ขนาด (4x5)

array([[ 6, 10,  9,  9,  9],
       [ 9,  7,  6,  5,  8],
       [ 9,  6,  5,  6, 10],
       [ 5, 10,  6,  7,  9]])