<a href="https://colab.research.google.com/github/pondbaahh/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np # package สำหรับทำงานกับ ข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ Matrix)

### Numpy Array

### สร้าง numpy array (matrix) จาก list

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) #สร้าง numpy array ที่มี2 แถว 3 หลัก

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

##matrix transpose

In [6]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

##สร้าง matrix เริ่มต้น (zeros,ones)

In [7]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
np_200 = 200*np.ones((4,7))
np_200  # เอา 200 มาคูณ

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง Matrix random 

In [10]:
np.random.randn(5,5)  #random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[-0.36723701,  0.18380271, -0.36478579, -0.72060602, -0.54449287],
       [-0.60122814, -1.65474072,  0.06808035,  0.43893742,  0.35318205],
       [ 1.08808686,  1.08985599,  2.43643021, -1.74137951, -0.57394536],
       [ 0.00862127,  0.36332344, -1.39171756, -1.38108333,  0.296425  ],
       [-2.63984367,  0.22161778, -2.31946923, -1.06860456, -1.27613561]])

In [11]:
2+(5*np.random.randn(3,3)) #random เลขมาจาก normal distribution ที่มี mu=2 std=5

array([[ -3.43115376,   2.99941411,   7.41592046],
       [-10.90873066,  -2.00675912,   6.83748763],
       [  6.92069514,   2.10788559,  -4.9753519 ]])

In [12]:
np.random.randint(5,11,(4,5)) #random เลขจำนวนเต็ม ระหว่าง[5,11] ขนาด (4x5)

array([[ 9, 10,  8,  8,  6],
       [ 7, 10,  9,  5,  8],
       [ 7,  9,  7,  5, 10],
       [ 9,  9,  9,  6,  7]])

## matrix poroperties

In [13]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np_a.T #ทำการ transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
1 + np_a #เอาตัวเลขมาบวกกับ matrix

array([[2, 3, 4],
       [5, 6, 7]])

In [16]:
2 * np_a #เอาตัวเลขมาคูณกับ matrix

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [17]:
np_c = np.array([[6,5,4],[3,2,1]])
np_c

array([[6, 5, 4],
       [3, 2, 1]])

In [18]:
np_a + np_c #เอา matrix มาบวกกับ matrix

array([[7, 7, 7],
       [7, 7, 7]])

In [19]:
np_a.shape #ดูขนาดได้ 2*3

(2, 3)

In [20]:
np_c.shape #ดูขนาดได้ 2*3

(2, 3)

In [21]:
np.dot(np_a,np_c) #การคูณ matrix (a,b) x (b,c) = (a,c)
#หลักของตัวหน้า เท่า แถวของตัวหลัง ถึงคูณกันได้

ValueError: ignored

In [22]:
np_c.T

array([[6, 3],
       [5, 2],
       [4, 1]])

In [24]:
np.dot(np_a,np_c.T)  #การคูณ matrix (a,b) x (b,c) = (a,c)

array([[28, 10],
       [73, 28]])

## Indexing & Slicing

In [25]:
np_a # เริ่มจากแถว 0 ,1 หลัก 0,1,2

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np_a[1,1]

5

In [27]:
np_a[:2,:2]

array([[1, 2],
       [4, 5]])

In [28]:
np_a[0,:]

array([1, 2, 3])

## Useful Functions

In [30]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
np.sum(np_a) #การวมเลขของ np_a

21

In [31]:
np.sum(np_a,axis=0) #axis คือการเอาค่าในแกนตั้งมารวมกัน

array([5, 7, 9])

In [32]:
np.sum(np_a,axis=1)#axis คือการเอาค่าในแกนนอนมารวมกัน

array([ 6, 15])

In [35]:
np.mean(np_a) #หาค่าmean

3.5

In [36]:
np.mean(np_a,axis=0) #หา mean ของ column

array([2.5, 3.5, 4.5])

### วนลูปเอง

summation

In [41]:
np_a.shape

(2, 3)

In [40]:
sum_all = 0

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all = sum_all + np_a[row,col]
        print(f'we are at row={row},col={col} np_a[{row},{col}]={np_a[row,col]} sum_all={sum_all}')
print(sum_all)        

we are at row=0,col=0 np_a[0,0]=1 sum_all=1
we are at row=0,col=1 np_a[0,1]=2 sum_all=3
we are at row=0,col=2 np_a[0,2]=3 sum_all=6
we are at row=1,col=0 np_a[1,0]=4 sum_all=10
we are at row=1,col=1 np_a[1,1]=5 sum_all=15
we are at row=1,col=2 np_a[1,2]=6 sum_all=21
21


np.sum(np_a,axis=0)

In [46]:
sum_all = np.zeros(np_a.shape[1])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[col] = sum_all[col] + np_a[row,col]     
print(sum_all) 

[5. 7. 9.]


Quiz กลุ่ม

วนลูปหาค่า


* np.sum(np_a,axis=1) sukuna 
* np.mean(np_a) i love อ.ต้น 
* np.mean(np_a,axis=0) natashar 
* np.mean(np_a,axis=1) teletubby
* np.max(np_a) numba one 
* np.max(np_a,axis=0) เอกาไร้สติ 
* np.max(np_a,axis=1) sandbox 
* np.min(np_a) ลูกหมี 
* np.min(np_a,axis=0) wakame 
* np.min(np_a,axis=1) แมวส้ม 



In [48]:
sum_all = np.zeros(np_a.shape[0])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[row] = sum_all[row] + np_a[row,col]     
print(sum_all) 

[ 6. 15.]


In [55]:
#np.mean(np_a,axis=0)
mean_all = np.zeros(np_a.shape[1])
for row in range(np_a.shape[0]):
     for col in range(np_a.shape[1]):
          mean_all[col] = mean_all[col] + np_a[row,col]/np_a.shape[0]
print(mean_all)

[2.5 3.5 4.5]


In [56]:
#np.mean(np_a,axis=1)
sum_all = np.zeros(np_a.shape[0])
for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]): 
        sum_all[row] = sum_all[row] + np_a[row,col]
sum_all = sum_all/np_a.shape[1]
print(sum_all)

[2. 5.]


In [57]:
#np.max(np_a)
max_a = -100000000
for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if np_a[row,col] > max_a :
            max_a = np_a[row,col]
print(max_a)


6


In [58]:
### 10. np.min(np_a,axis=1)
min_row = np.zeros(np_a.shape[0])
for row in range(np_a.shape[0]):
   min_row[row] = min(np_a[row,:])
print(min_row)

[1. 4.]


In [59]:
# np.min(np_a,axis=0)
min_all = np.zeros(np_a.shape[1])

for col in range(np_a.shape[1]):
    min_all[col] = min(np_a[:,col])
print(min_all)

[1. 2. 3.]


In [60]:
# np.min(np_a) 
minV = 100000
for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if np_a[row,col] < minV:
            minV = np_a[row,col]
print(minV)

1


In [61]:
# np.max(np_a,axis=0)
max_all = -100000 * np.ones(np_a.shape[1])
for col in range(np_a.shape[1]):
    for row in range(np_a.shape[0]):
        if np_a[row,col] > max_all[col]: 
            max_all[col] = np_a[row,col]
print(max_all)

[4. 5. 6.]


In [62]:
#np.mean(np_a)
mean_all = 0
for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        mean_all = mean_all + np_a[row,col]
mean_all = mean_all/(np_a.shape[0]*np_a.shape[1])
print(mean_all)

3.5


In [63]:
# np.max(np_a,axis=1)
max_all = np.zeros(np_a.shape[0])
for row in range(np_a.shape[0]):
    max_all[row] = max(np_a[row,:])
print(max_all)

[3. 6.]
